config/routes.rb
Rails.application.routes.draw do
  resources :contact_submissions
  resource :session
  resources :passwords, param: :token
  resources :posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "home#index"

  get "contact", to: "home#contact"

  get "splitboarding", to: "posts#splitboarding"
  get "projects", to: "posts#projects"
end

app/models/contact_submission.rb
class ContactSubmission < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :message, presence: true, length: { minimum: 10 }
end

app/controllers/contact_submissions_controller.rb
class ContactSubmissionsController < ApplicationController
  before_action :set_contact_submission, only: %i[ show edit update destroy ]
  allow_unauthenticated_access only: %i[ new ]

  # GET /contact_submissions or /contact_submissions.json
  def index
    @contact_submissions = ContactSubmission.all
  end

  # GET /contact_submissions/1 or /contact_submissions/1.json
  def show
  end

  # GET /contact_submissions/new
  def new
    @contact_submission = ContactSubmission.new
  end

  # GET /contact_submissions/1/edit
  def edit
  end

  # POST /contact_submissions or /contact_submissions.json
  def create
    @contact_submission = ContactSubmission.new(contact_submission_params)

    respond_to do |format|
      if @contact_submission.save
        ContactMailer.new_contact(@contact_submission).deliver_later
        format.html { redirect_to @contact_submission, notice: "Contact submission was successfully sent." }
        format.json { render :show, status: :created, location: @contact_submission }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @contact_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contact_submissions/1 or /contact_submissions/1.json
  def update
    respond_to do |format|
      if @contact_submission.update(contact_submission_params)
        format.html { redirect_to @contact_submission, notice: "Contact submission was successfully updated." }
        format.json { render :show, status: :ok, location: @contact_submission }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @contact_submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contact_submissions/1 or /contact_submissions/1.json
  def destroy
    @contact_submission.destroy!

    respond_to do |format|
      format.html { redirect_to contact_submissions_path, status: :see_other, notice: "Contact submission was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact_submission
      @contact_submission = ContactSubmission.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def contact_submission_params
      params.expect(contact_submission: [ :name, :email, :subject, :message ])
    end
end

app/helpers/contact_submissions_helper.rb
module ContactSubmissionsHelper
end

app/views/contact_submissions/_contact_submission.html.erb
<div id="<%= dom_id contact_submission %>">
  <p>
    <strong>Name:</strong>
    <%= contact_submission.name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= contact_submission.email %>
  </p>

  <p>
    <strong>Subject:</strong>
    <%= contact_submission.subject %>
  </p>

  <p>
    <strong>Message:</strong>
    <%= contact_submission.message %>
  </p>

</div>

app/views/contact_submissions/_form.html.erb
<%= form_with(model: contact_submission) do |form| %>
  <% if contact_submission.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(contact_submission.errors.count, "error") %> prohibited this contact form from being sent:</h2>

      <ul>
        <% contact_submission.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :subject, style: "display: block" %>
    <%= form.text_field :subject %>
  </div>

  <div>
    <%= form.label :message, style: "display: block" %>
    <%= form.textarea :message %>
  </div>

  <div>
    <%= form.submit "Send", class: "button" %>
  </div>
<% end %>

app/views/contact_submissions/edit.html.erb
<% content_for :title, "Editing contact submission" %>

<h1>Editing contact submission</h1>

<%= render "form", contact_submission: @contact_submission %>

<br>

<div>
  <%= link_to "Show this contact submission", @contact_submission %> |
  <%= link_to "Back to contact submissions", contact_submissions_path %>
</div>

app/views/contact_submissions/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Contact submissions" %>

<h1>Contact submissions</h1>

<div id="contact_submissions">
  <% @contact_submissions.each do |contact_submission| %>
    <%= render contact_submission %>
    <p>
      <%= link_to "Show this contact submission", contact_submission %>
    </p>
  <% end %>
</div>

<%= link_to "New contact submission", new_contact_submission_path %>

app/views/contact_submissions/new.html.erb
<% content_for :title, "New contact submission" %>

<h1>lets get in touch!</h1>

<br>

<%= render "form", contact_submission: @contact_submission %>

<br>

<% if authenticated? %>
  <div>
    <%= link_to "Back to contact submissions", contact_submissions_path %>
  </div>
<% end %> 

app/views/contact_submissions/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @contact_submission %>

<div>
  <%= link_to "Edit this contact submission", edit_contact_submission_path(@contact_submission) %> |
  <%= link_to "Back to contact submissions", contact_submissions_path %>

  <%= button_to "Destroy this contact submission", @contact_submission, method: :delete %>
</div>